### ISSUE TITLE
why gcode command in test.gc file most start with 'X' not 'G'?

### ISSUE THREAD

**Issue by overheat** [johannesnoordanus/image2gcode#2]
Hi,

I am a newbie and what to use this python lib to convert image to gcode for CNC.
But I think most 3D printer moving command should start with 'G', like `G1`

I saw most gcode command in test.gc file most start with 'X'. Cloud you please explain it?
And how to generate gcode for CNC?

**Comment by johannesnoordanus** [comment]
Hi,

First of all image2gcode converts images to grbl v1.1 CNC machines.
Specific: 2-axis laser cutters/engravers. Images are 2D after all.
The output isn’t suitable for 3-axis machines like 3D printers.

To answer your question: you are right that a ‘move’ starts with a ‘G0/1’
command first followed by its destination (X or Y in this case)
coordinates. But consecutive moves can be written down in a short form
without repeating the G command. So when you start with mode G0, X and Y
coordinates following it on consecutive lines, will move the head to those
coordinates.

You can generate gcode for 3D printers using a program like Cura. You first
have to create a 3D model using a program like OpenScad (or a multitude of
others) and export it to an .stl file and hand it over to Cura.
Lots of other 3D modeler programs have easy option to print in 3D.

Regards,
Johannes
